<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120531165158 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE story ADD boardId INT DEFAULT NULL");
        $this->addSql("ALTER TABLE story ADD CONSTRAINT FK_EB56043839393B26 FOREIGN KEY (boardId) REFERENCES board(boardId)");
        $this->addSql("CREATE INDEX IDX_EB56043839393B26 ON story (boardId)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE story DROP FOREIGN KEY FK_EB56043839393B26");
        $this->addSql("DROP INDEX IDX_EB56043839393B26 ON story");
        $this->addSql("ALTER TABLE story DROP boardId");
    }
}
