<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120730171416 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE chatMessage (chatMessageId INT AUTO_INCREMENT NOT NULL, content LONGTEXT DEFAULT NULL, datetime DATETIME NOT NULL, boardId INT DEFAULT NULL, userId INT DEFAULT NULL, INDEX IDX_E7EFD94139393B26 (boardId), INDEX IDX_E7EFD94164B64DCC (userId), PRIMARY KEY(chatMessageId)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE chatMessage ADD CONSTRAINT FK_E7EFD94139393B26 FOREIGN KEY (boardId) REFERENCES board (boardId)");
        $this->addSql("ALTER TABLE chatMessage ADD CONSTRAINT FK_E7EFD94164B64DCC FOREIGN KEY (userId) REFERENCES user (userId)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE chatMessage");
    }
}
