<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120502222917 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ticket (ticketId INT AUTO_INCREMENT NOT NULL, colour VARCHAR(45) NOT NULL, cssHash VARCHAR(6) NOT NULL, content LONGTEXT NOT NULL, x INT NOT NULL, y INT NOT NULL, parent INT NOT NULL, PRIMARY KEY(ticketId)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ticket");
    }
}
