<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121108002847 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE board ADD teamId INT DEFAULT NULL");
        $this->addSql("ALTER TABLE board ADD CONSTRAINT FK_58562B47D8528F51 FOREIGN KEY (teamId) REFERENCES team (teamId);");
        $this->addSql("CREATE INDEX IDX_58562B47D8528F51 ON board (teamId)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE board DROP FOREIGN KEY FK_58562B47D8528F51");
        $this->addSql("DROP INDEX IDX_58562B47D8528F51 ON board");
        $this->addSql("ALTER TABLE board DROP teamId");
    }
}
