<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120722232704 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE invitation CHANGE teamId teamId INT DEFAULT NULL");
        $this->addSql("ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2D8528F51 FOREIGN KEY (teamId) REFERENCES team (teamId)");
        $this->addSql("CREATE INDEX IDX_F11D61A2D8528F51 ON invitation (teamId)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A2D8528F51");
        $this->addSql("DROP INDEX IDX_F11D61A2D8528F51 ON invitation");
        $this->addSql("ALTER TABLE invitation CHANGE teamId teamId INT NOT NULL");
    }
}
