<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120530164416 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ticket ADD boardId INT DEFAULT NULL");
        $this->addSql("ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA339393B26 FOREIGN KEY (boardId) REFERENCES board(boardId)");
        $this->addSql("CREATE INDEX IDX_97A0ADA339393B26 ON ticket (boardId)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA339393B26");
        $this->addSql("DROP INDEX IDX_97A0ADA339393B26 ON ticket");
        $this->addSql("ALTER TABLE ticket DROP boardId");
    }
}
