<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121031204142 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE storyStatus (statusId INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(statusId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("INSERT INTO storyStatus (name) VALUES ('New'), ('In Progress'), ('Testable'), ('Done')");
        $this->addSql("ALTER TABLE story ADD statusId INT DEFAULT 1");
        $this->addSql("ALTER TABLE story ADD CONSTRAINT FK_EB560438F112F078 FOREIGN KEY (statusId) REFERENCES storyStatus (statusId)");
        $this->addSql("CREATE INDEX IDX_EB560438F112F078 ON story (statusId)");
        $this->addSql('UPDATE story SET statusId = 1 WHERE statusId IS NULL');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE story DROP FOREIGN KEY FK_EB560438F112F078");
        $this->addSql("DROP TABLE storyStatus");
        $this->addSql("DROP INDEX IDX_EB560438F112F078 ON story");
        $this->addSql("ALTER TABLE story DROP statusId");
    }
}
