"""empty message

Revision ID: 1997bf55ea3c
Revises: cf4544a4a26
Create Date: 2015-02-05 12:35:42.924239

"""

# revision identifiers, used by Alembic.
revision = '1997bf55ea3c'
down_revision = 'cf4544a4a26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'content')
    ### end Alembic commands ###
