"""empty message

Revision ID: 29bc43a023ef
Revises: 1997bf55ea3c
Create Date: 2015-02-05 12:40:06.608205

"""

# revision identifiers, used by Alembic.
revision = '29bc43a023ef'
down_revision = '1997bf55ea3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_column', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_column', 'order')
    ### end Alembic commands ###
